"""Assemble the public code-and-results release (GitHub + Zenodo) in release/ and the Zenodo zips in submission/.
Only code that produces reported numbers, the aggregate result tables, and the documentation are included. Per-window
tables derived from the EvEMTBench records are NOT redistributed (data licence unclear: CC BY 4.0 in the benchmark
repository, CC BY-NC-ND 4.0 on the dataset paper); every one of them is regenerated by the scripts.
Usage: python src/paper/build_release.py"""
import shutil
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REL = ROOT / "release"
SUB = ROOT / "submission"
EXCLUDE_C1 = {"hybrid_ha.py", "hybrid_ha2.py", "hybrid_hb.py", "hybrid_hc.py", "pipeline_hcp2.py", "phys_loop.py",
              "teacher.py", "one_ended.py"}
RESULTS = ["c1_ha2_eval.csv", "c1_ha2_noise.csv", "c1_adapt_ingrid.csv", "c1_zs_MV.csv", "c1_equal_info.csv",
           "c1_adapt_equal_info.csv", "c1_zs_equal_info_MV.csv", "c1_classical_report.csv", "c1_chain_eval.csv",
           "c1_cond_summary.csv", "c1_cond_rho_bins.csv", "c1_ablations.csv", "c1_ablation_a3_fixed.csv",
           "c1_fig4_data.csv", "c1_review_checks.csv", "c1_review_phasor_bytime.csv", "c1_review_suonan.csv",
           "c1_review_sync_us.csv", "c1_i0_guard_patch.csv", "c1_i0_guard_check.csv", "c1_equal_info_preds_check.csv",
           "validate_ha2_ingrid_counts.csv", "validate_ha2_guard_oldnew.csv", "validate_ha2_neural_runs.csv",
           "validate_ha2_ingrid_neural_summary.csv", "c1_revamp_stats.csv", "c1_runtime.csv",
           "validate_ha2_part9_summary.csv", "validate_ha2_part9cmp.csv",
           "c1_two_end_learn.csv", "c1_prof_m6.csv", "c1_prof_m6_extra.csv", "validate_part10b.csv",
           "c1_prof2.csv", "validate_part11.csv", "c1_two_end_chain.csv", "c1_two_end_chain_selfcheck.csv"]
DOCS = {"claudedocs/c1_hybrid_design.md": "preregistration_log.md", "research/C1_GATE.md": "results_ledger.md",
        "research/VALIDATION_HA2.md": "independent_validation.md"}


def copy_tree(src, dst, keep):
    for f in sorted(src.iterdir()):
        if f.is_file() and keep(f):
            dst.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, dst / f.name)


def main():
    for d in ("src", "results", "docs"):
        shutil.rmtree(REL / d, ignore_errors=True)
    copy_tree(ROOT / "src" / "c1", REL / "src" / "c1",
              lambda f: f.suffix in (".py", ".sh") and f.name not in EXCLUDE_C1)
    copy_tree(ROOT / "src" / "paper", REL / "src" / "paper", lambda f: f.suffix == ".py")
    copy_tree(ROOT / "src" / "validate_ha2", REL / "src" / "validate_ha2", lambda f: f.suffix == ".py")
    copy_tree(ROOT / "src" / "validate_c1", REL / "src" / "validate_c1", lambda f: f.name in ("part10b.py", "part11.py"))
    (REL / "results").mkdir(parents=True, exist_ok=True)
    missing = [r for r in RESULTS if not (ROOT / "results" / r).exists()]
    assert not missing, missing
    for r in RESULTS:
        shutil.copy2(ROOT / "results" / r, REL / "results" / r)
    (REL / "docs").mkdir(exist_ok=True)
    for s, d in DOCS.items():
        shutil.copy2(ROOT / s, REL / "docs" / d)
    SUB.mkdir(exist_ok=True)
    zips = {"zenodo_code.zip": ["src", "README.md", "LICENSE", "requirements.txt", "CITATION.cff"],
            "zenodo_results_docs.zip": ["results", "docs"]}
    for name, parts in zips.items():
        with zipfile.ZipFile(SUB / name, "w", zipfile.ZIP_DEFLATED) as z:
            for p in parts:
                q = REL / p
                files = [q] if q.is_file() else sorted(x for x in q.rglob("*") if x.is_file())
                for f in files:
                    z.write(f, f.relative_to(REL).as_posix())
        print(f"{name}: {(SUB / name).stat().st_size / 1e6:.2f} MB")
    n = sum(1 for _ in (REL / "src").rglob("*.py"))
    print(f"release/: {n} python files, {len(RESULTS)} result tables, {len(DOCS)} docs")


if __name__ == "__main__":
    main()
